# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Rose-DBx-TestDB
version:      0.03
version_from: lib/Rose/DBx/TestDB.pm
installdirs:  site
requires:
    DBD::SQLite:                   1.08
    File::Temp:                    0
    Rose::DB:                      0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
